### PR TITLE
Solution for issue #8

### PR DESCRIPTION
**Pull request by TylorS**

### CODE REVIEW

**Comment by TylorS** [comment]
This commit currently breaks the performance test

**Comment by staltz** [comment]
As I mentioned to Tylor in a chat:

Because Motorcycle is all about performance, I'd say try removing wrapTopLevelVTree, but try to make isomorphic rendering with Motorcycle, such that the client-side can skip the first rendering
On the other hand, it might be ok to just allow the client-side to rerender in vain, because it's so fast to do so that it doesn't matter, while 30fps does matter compared to 65fps
Anyway, wrapTopLevelVTree is not important
The use case it is solving is important
Just dig into that commit message to see what the use case is

**Comment by TylorS** [comment]
With the last commit changing around the operators significantly helps with the rendering speed. I'm finding ~55fps now. Still down ~10FPS but it's a step in the right direction. I believe that it's a feature worth keeping for all of the reasons you mentioned in that commit referenced in #8 .

Open to discussion, but I think more optimizations can be found as we grab better understandings of `most` and performance can be solved without removing this feature.

**Comment by TylorS** [comment]
I'm having trouble tracking down what is happening exactly, but I'm losing some events in the performance test

**Comment by Frikki** [comment]
How are things with this?

**Pull request closed without merging**
