### PR TITLE
perf(): Remove Array.prototype.slice.call

### PR DESCRIPTION
**Pull request by TylorS**
Remove use of Array.prototype.slice.call() for a more
performant use of a for-loop.

### CODE REVIEW

**Comment by TylorS** [comment]
Actually, I think it would be easier simply to return the nodeList as fast.js' methods work on array-like objects

**Comment by TylorS** [comment]
Just kidding, returning the nodeList blows up the tests :smile:

**Comment by Frikki** [comment]
You’re such a joker :D

**Comment by TylorS** [comment]
It was worth a try, I couldn't resolve all the issues.

**Pull request merged**
